services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie
    [...]
    depends_on:
      - database

  database:
    image: postgres
    [...]

  bring-api:
    image: ghcr.io/felixschndr/mealie-bring-api:latest
    ports:
      - "12001:8742" # external:internal
    environment:
      # Take a look at the README for an explanation of the environment variables
      # If you are using the array style instead of the map style to define your env variable be sure
      # to NOT quote the values, see https://docs.docker.com/reference/compose-file/services/#environment
      BRING_USERNAME: "myuser@myemailprovider.com"
      BRING_PASSWORD: "mysupersecretpassword"
      BRING_LIST_NAME: "My list has some spaces in it"

      MEALIE_BASE_URL: "https://mealie.yourdomain.com"
      MEALIE_API_KEY: "ey....."
      MEALIE_SHOPPING_LIST_UUID: "c040c0f4-5336-4a0a-b0ac-24114b457301"

      LOG_LEVEL: INFO

      HTTP_HOST: 0.0.0.0
      HTTP_PORT: 8742
      HTTP_BASE_PATH: ""
    cap_drop:
      - ALL
    depends_on:
      - mealie
